host: 0.0.0.0
title: Christian Figueroa
email: figgchristian@gmail.com
description: >-
baseurl: ""
url: ""
social:
  github:
    username: figgchristian
    link: https://github.com/figgchristian
  linkedin:
    username: figgchristian
    link: https://linkedin.com/in/figgchristian
collections:
  - spotlight
exclude:
  - projects/fonttex/node_modules
  - vendor

sass:
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - package.json
  - package-lock.json
  - gulpfile.js
  - fontawesome/