title: Christian Figueroa
email: figgchristian@gmail.com
description: >-
  
baseurl: ""
url: ""
social:
  - instagram:
    - username: figgchristian
      link: https://instagram.com/figgchristian
  - github:
    - username: ChristianFigueroa
      link: https://github.com/ChristianFigueroa
  - linkedin:
    - username: figgchristian
      link: https://linkedin.com/in/figgchristian

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
