host: 0.0.0.0
title: Christian Figueroa
email: figgchristian@gmail.com
description: >-
baseurl: ""
url: ""
social:
  github:
    username: ChristianFigueroa
    link: https://github.com/ChristianFigueroa
  linkedin:
    username: figgchristian
    link: https://linkedin.com/in/figgchristian
collections:
  - spotlight
exclude:
  - projects/fonttex/node_modules
  - vendor

style:
  color:
    background: "#26292C"
    accent: "#00849D"
    link: "#66D9EF"
    text: "#FFF"
    code:
      background: "#26292C"
      lineHighlight: "#202325"
      purple: "#AE81FF"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - package.json
  - package-lock.json
  - gulpfile.js
  - fontawesome/